# Generated by Django 4.2.11 on 2026-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IadeKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karel_is_kolu', models.CharField(blank=True, max_length=100)),
                ('musteri_iade_nedeni', models.CharField(blank=True, max_length=500)),
                ('musteri', models.CharField(blank=True, max_length=200)),
                ('musteri_bildirim_no', models.CharField(blank=True, max_length=100)),
                ('bildirim_tarihi', models.CharField(blank=True, max_length=20)),
                ('musteri_stok_no', models.CharField(blank=True, max_length=100)),
                ('karel_stok_no', models.CharField(blank=True, max_length=100)),
                ('urun_tanimi', models.CharField(blank=True, max_length=200)),
                ('proje', models.CharField(blank=True, max_length=100)),
                ('bildirilen_seri_no', models.CharField(blank=True, max_length=100)),
                ('kaliteye_gelis_tarihi', models.CharField(blank=True, max_length=20)),
                ('uretim_aktarim_tarihi', models.CharField(blank=True, max_length=20)),
                ('sevkiyat_depoya_aktarim_tarihi', models.CharField(blank=True, max_length=20)),
                ('kalite_kontrol_8d', models.CharField(blank=True, max_length=20)),
                ('eco_dk_kontrolu', models.CharField(blank=True, max_length=20)),
                ('kaynaginda_denetim', models.CharField(blank=True, max_length=20)),
                ('hata_turu', models.CharField(blank=True, max_length=200)),
                ('mutabakat_durumu', models.CharField(blank=True, max_length=50)),
                ('nihai_garanti_mutabakat', models.CharField(blank=True, max_length=20)),
                ('musteri_onarim_mutabakat', models.CharField(blank=True, max_length=20)),
                ('ilk_sevk_tarihi', models.CharField(blank=True, max_length=20)),
                ('garanti_durumu', models.CharField(blank=True, max_length=50)),
                ('faturali_faturasiz', models.CharField(blank=True, max_length=20)),
                ('is_emri_acilis_tarihi', models.CharField(blank=True, max_length=20)),
                ('is_emri', models.CharField(blank=True, max_length=100)),
                ('musteri_irsaliye_no', models.CharField(blank=True, max_length=100)),
                ('musteri_irsaliye_tarihi', models.CharField(blank=True, max_length=20)),
                ('musteri_siparis_no', models.CharField(blank=True, max_length=100)),
                ('gelen_urun_seri_no', models.CharField(blank=True, max_length=100)),
                ('karel_irsaliye_no', models.CharField(blank=True, max_length=100)),
                ('iade_sevk_tarihi', models.CharField(blank=True, max_length=20)),
                ('hedeflenen_onarim_tarihi', models.CharField(blank=True, max_length=20)),
                ('gerceklesen_onarim_tarihi', models.CharField(blank=True, max_length=20)),
                ('onarim_aciklama', models.TextField(blank=True)),
                ('proforma_numarasi', models.CharField(blank=True, max_length=100)),
                ('kaliteye_aktarim_tarihi', models.CharField(blank=True, max_length=20)),
                ('eco_dk_kontrolu_uretim', models.CharField(blank=True, max_length=20)),
                ('hedeflenen_hata_tespit_tarihi', models.CharField(blank=True, max_length=20)),
                ('gerceklesen_hata_tespit_tarihi', models.CharField(blank=True, max_length=20)),
                ('uretim_bulgusu', models.TextField(blank=True)),
                ('malzeme_planlama', models.CharField(blank=True, max_length=500)),
                ('nff_durumu', models.CharField(blank=True, max_length=20)),
                ('nihai_garanti_durumu', models.CharField(blank=True, max_length=50)),
                ('bekleme_nedeni', models.CharField(blank=True, max_length=50)),
                ('durum', models.CharField(blank=True, max_length=50)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100, unique=True)),
                ('roller', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
    ]
