# Generated by Django 4.2.11 on 2026-06-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IadeKayitGecmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degistiren', models.CharField(blank=True, max_length=100)),
                ('degisiklik_tarihi', models.DateTimeField(auto_now_add=True)),
                ('eski_veri', models.JSONField()),
                ('ana_kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis', to='iade_app.iadekayit')),
            ],
            options={
                'ordering': ['-degisiklik_tarihi'],
            },
        ),
    ]
