# Generated by Django 4.2.11 on 2026-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0002_iadekayitgecmis'),
    ]

    operations = [
        migrations.CreateModel(
            name='IadeKayitSilindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_verisi', models.JSONField()),
                ('silen_kullanici', models.CharField(blank=True, max_length=100)),
                ('silinme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Silinen Kayıt',
                'verbose_name_plural': 'Silinen Kayıtlar',
                'ordering': ['-silinme_tarihi'],
            },
        ),
    ]
