# Generated by Django 6.0.6 on 2026-06-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0003_iadekayitsilindi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciSilindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=150)),
                ('roller', models.CharField(blank=True, default='', max_length=255)),
                ('silinme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('silen_kullanici', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
    ]
