# Generated by Django 6.0.6 on 2026-06-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0004_kullanicisilindi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kullanicisilindi',
            options={'ordering': ['-silinme_tarihi'], 'verbose_name': 'Silinen Kullanıcı', 'verbose_name_plural': 'Silinen Kullanıcılar'},
        ),
    ]
