# Generated by Django 6.0.6 on 2026-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0005_alter_kullanicisilindi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciYetki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100, unique=True)),
                ('roller', models.CharField(max_length=500)),
            ],
        ),
    ]
