# Generated by Django 6.0.6 on 2026-06-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0006_kullaniciyetki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KullaniciYetki',
        ),
        migrations.AddField(
            model_name='kullanici',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
