# Generated by Django 6.0.6 on 2026-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0007_delete_kullaniciyetki_kullanici_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='kullanici_adi',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
