# Generated by Django 6.0.6 on 2026-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0008_alter_kullanici_kullanici_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
