# Generated by Django 4.2.11 on 2026-08-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iade_app', '0009_kullanici_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='IadeSeriKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(blank=True, max_length=100)),
                ('is_emri', models.CharField(blank=True, max_length=100)),
                ('durum', models.CharField(blank=True, max_length=50)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ana_kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_seriler', to='iade_app.iadekayit')),
            ],
            options={
                'verbose_name': 'Ek Seri/Kalem',
                'verbose_name_plural': 'Ek Seri/Kalemler',
                'ordering': ['id'],
            },
        ),
    ]
